### List events
GET https://gamma-api.polymarket.com/events

### Get event by id
GET https://gamma-api.polymarket.com/events/{id}

### List markets
GET https://gamma-api.polymarket.com/markets

### Get market by id
GET https://gamma-api.polymarket.com/markets/{id}

### Get event id from slug
GET https://gamma-api.polymarket.com/events/slug/fed-decision-in-january



